name: Build and Deploy mern application

on:
  push:
    branches: [ "main" ]
  
env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  PORT: ${{ secrets.PORT }}
  REACT_APP_API: ${{ secrets.REACT_APP_API}}

jobs:
  build:

    runs-on: self-hosted

    # strategy:
    #   matrix:
    #     node-version: [18.18.0]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Nodejs version
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0
        cache: 'npm'
    - name: Install and Test Client
      working-directory: ./client
      run: |
          npm install
          export REACT_APP_API=$REACT_APP_API
          touch .env
          echo REACT_APP_API =${{ secrets.REACT_APP_API }} >> .env
      
    - name: Install and Test Server
      working-directory: ./
      run: |
          npm install
          export  MONGO_URL=$MONGO_URL
          export PORT=$PORT
          export JWT_SECRET=$JWT_SECRET
          touch .env
          echo   MONGO_URL =${{ secrets.MONGO_URL }} >> .env
          echo   PORT =${{ secrets.PORT }} >> .env
          echo   REACT_APP_API =${{ secrets.REACT_APP_API}} >> .env

   

   

    - name: Build Server Docker Image
      working-directory: ./
      run: |
          docker build -t hima10shree/coding_platform-githubactions:latest .


    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Images to Docker Hub
      run: 
          docker push  hima10shree/coding_platform-githubactions:latest

    
    - name: Deploy the aplication to ec2 instance
      run:  
        docker container run -d -p 3000:3000 -p 8000:8000 hima10shree/coding_platform-githubactions:latest
        

          
          
          

    
      
